// MALINDRA PHASE 2
// app/blog/[slug]/page.tsx
// Static article page — rendered at build time via generateStaticParams.
// Phase 2: SIGINT cross-referencing injected at build time, locale-aware OG image.
// No SSR, no runtime fetch. Pure static HTML export.

import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { getAllSlugs, getArticleContent, getBlogData } from '@/lib/blog-data';
import { markdownToHtml, extractToc } from '@/lib/markdown';
import { findRelatedSignals, extractEntities, type Signal } from '@/lib/sigint';
import ReadingProgress from '@/app/blog/components/ReadingProgress';
import TableOfContents from '@/app/blog/components/TableOfContents';
import SigintCrossRef from '@/components/SigintCrossRef';

// ── Static generation ─────────────────────────────────────────────────────────

export async function generateStaticParams() {
  const slugs = await getAllSlugs();
  return slugs.map((slug) => ({ slug }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const article = await getArticleContent(slug);
  if (!article) return { title: 'Not Found' };

  const ogDescription = article.excerpt || article.description;

  // Per-article locale-aware OG image — generated by scripts/generate-og-images.mjs
  // Falls back to default if not generated yet.
  const ogImagePath = `/og/en/${slug}.png`;

  return {
    title: article.title,
    description: ogDescription,
    alternates: {
      canonical: `/blog/${slug}`,
    },
    openGraph: {
      title: article.title,
      description: ogDescription,
      type: 'article',
      publishedTime: article.date,
      tags: article.tags,
      images: [
        {
          url: ogImagePath,
          width: 1200,
          height: 630,
          alt: article.title,
        },
      ],
    },
    twitter: {
      card: 'summary_large_image',
      title: article.title,
      description: ogDescription,
    },
  };
}

// ── Page component ────────────────────────────────────────────────────────────

export default async function ArticlePage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const article = await getArticleContent(slug);
  if (!article) notFound();

  const [html, toc, { articles }] = await Promise.all([
    markdownToHtml(article.rawMarkdown),
    Promise.resolve(extractToc(article.rawMarkdown)),
    getBlogData(),
  ]);

  // Determine prev/next articles (by date order)
  const currentIdx = articles.findIndex((a) => a.slug === slug);
  const prevArticle = currentIdx > 0 ? articles[currentIdx - 1] : null;
  const nextArticle = currentIdx < articles.length - 1 ? articles[currentIdx + 1] : null;

  // Build Signal objects for cross-referencing
  const currentSignal: Signal = {
    slug: article.slug,
    title: article.title,
    tags: article.tags,
    entities: article.entities ?? extractEntities(article.rawMarkdown),
    date: article.date,
    category: article.category,
    excerpt: article.excerpt,
  };

  const allSignals: Signal[] = articles.map((a) => ({
    slug: a.slug,
    title: a.title,
    tags: a.tags,
    entities: a.entities ?? [],
    date: a.date,
    category: a.category,
    excerpt: a.excerpt,
  }));

  const related = findRelatedSignals(currentSignal, allSignals, 3);

  const categoryLabel = article.category
    .replace(/-/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase());

  return (
    <>
      {/* Reading progress bar — client component */}
      <ReadingProgress />

      <div
        style={{
          display: 'grid',
          gridTemplateColumns: toc.length > 3 ? '1fr 220px' : '1fr',
          gap: 'var(--spacing-2xl)',
          maxWidth: '960px',
          margin: '0 auto',
          padding: 'var(--spacing-xl) var(--spacing-lg)',
          alignItems: 'start',
        }}
      >
        {/* ── Main article column ── */}
        <article>
          {/* Breadcrumb */}
          <nav
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: 'var(--spacing-sm)',
              marginBottom: 'var(--spacing-lg)',
            }}
          >
            <Link href="/blog" className="t-muted" style={{ fontSize: '13px' }}>
              Malindra
            </Link>
            <span className="t-muted" style={{ fontSize: '13px' }}>
              /
            </span>
            <Link
              href={`/archive/category/${article.category}`}
              className="t-muted"
              style={{ fontSize: '13px' }}
            >
              {categoryLabel}
            </Link>
            <span className="t-muted" style={{ fontSize: '13px' }}>
              /
            </span>
            <span className="t-muted" style={{ fontSize: '13px', color: 'var(--color-parchment)' }}>
              {article.title}
            </span>
          </nav>

          {/* Hero */}
          <div className="article-hero">
            <div className="t-eyebrow">SIGINT ANALYSIS</div>
            <h1 className="article-hero-title">{article.title}</h1>
            {article.description && (
              <p
                className="t-body"
                style={{ maxWidth: '640px', marginTop: 'var(--spacing-sm)' }}
              >
                {article.description}
              </p>
            )}
            <div className="article-hero-meta">
              <time dateTime={article.date}>
                {new Date(article.date).toLocaleDateString('en-US', {
                  year: 'numeric',
                  month: 'long',
                  day: 'numeric',
                })}
              </time>
              {article.readingMinutes > 0 && (
                <>
                  <span className="article-hero-meta-sep" />
                  <span>{article.readingMinutes} min read</span>
                </>
              )}
              {article.tags.length > 0 && (
                <>
                  <span className="article-hero-meta-sep" />
                  <div style={{ display: 'flex', gap: 'var(--spacing-xs)', flexWrap: 'wrap' }}>
                    {article.tags.slice(0, 4).map((tag) => (
                      <Link
                        key={tag}
                        href={`/archive/tag/${encodeURIComponent(
                          tag.toLowerCase().replace(/\s+/g, '-'),
                        )}`}
                        className="badge badge-hold"
                        style={{ textDecoration: 'none' }}
                      >
                        {tag}
                      </Link>
                    ))}
                  </div>
                </>
              )}
            </div>
          </div>

          {/* Article body */}
          <div
            className="prose"
            style={{ marginTop: 'var(--spacing-2xl)' }}
            dangerouslySetInnerHTML={{ __html: html }}
          />

          {/* SIGINT cross-references — injected at build time */}
          {related.length > 0 && <SigintCrossRef signals={related} locale="en" />}

          {/* Footer heritage tag + prev/next navigation */}
          <footer style={{ marginTop: 'var(--spacing-3xl)', paddingTop: 'var(--spacing-lg)', borderTop: '1px solid var(--color-border-default)' }}>
            <div className="t-heritage">
              Malindra · මලින්ද්‍ර
            </div>
            <div
              style={{
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
                marginTop: 'var(--spacing-lg)',
                flexWrap: 'wrap',
                gap: 'var(--spacing-sm)',
              }}
            >
              <Link href="/blog" className="btn btn-ghost" style={{ fontSize: '12px' }}>
                ← All Analysis
              </Link>
              <Link href="/archive" className="btn btn-ghost" style={{ fontSize: '12px' }}>
                Browse Archive →
              </Link>
            </div>

            {/* Unified prev/next article navigation */}
            {(prevArticle || nextArticle) && (
              <div className="article-nav">
                {prevArticle ? (
                  <Link href={`/blog/${prevArticle.slug}`} className="article-nav-link">
                    <span className="article-nav-label">&larr; Previous</span>
                    <span className="article-nav-title">{prevArticle.title}</span>
                  </Link>
                ) : <div />}
                {nextArticle ? (
                  <Link href={`/blog/${nextArticle.slug}`} className="article-nav-link article-nav-link--next">
                    <span className="article-nav-label">Next &rarr;</span>
                    <span className="article-nav-title">{nextArticle.title}</span>
                  </Link>
                ) : <div />}
              </div>
            )}
          </footer>
        </article>

        {/* ── Sidebar ToC — only shown when headings present ── */}
        {toc.length > 3 && <TableOfContents items={toc} />}
      </div>
    </>
  );
}
